// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accomodation: dynamic(() => import("./Accomodation")),
  attractions: dynamic(() => import("./Attractions")),
  contacts: dynamic(() => import("./Contacts")),
  details: dynamic(() => import("./Details")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  navigation: dynamic(() => import("./Navigation")),
};
